[BUGFIX] Replaced Long method with Integer
Methods couldn't be accessed because the Minified API uses `int` instead of `long`.
Would throw `Exception in thread "Thread-13" java.lang.NoSuchMethodError: org.rev317.min.api.methods.Skill.getRemaining()I`
Also formatted the code.